# Dockerfile

FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy everything from current dir (your PC) into /app (container)
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Flask default port
EXPOSE 5000

# Run your Flask app
CMD ["python", "app.py"]
